security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\AdminUser
                property: email

    role_hierarchy:
        ROLE_MANAGER: [ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            switch_user: { role: SUPER_ADMIN }
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginAuthenticator
            logout:
                path: app_logout

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home
                # Uncomment the next line if you want to enable CSRF protection for the login form
                # enable_csrf: true

            entry_point: App\Security\LoginAuthenticator

    access_control:
        - { path: ^/$, roles: [SUPER_ADMIN, ROLE_MANAGER] }
        - { path: ^/templates, roles: PUBLIC_ACCESS }
        - { path: ^/token, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/access, roles: PUBLIC_ACCESS }
        - { path: ^/manager/home, roles: [ROLE_MANAGER] }
