#WORK: OK
app_home:
    path: /
    controller: App\Controller\DefaultController::index

app_manager_redirect:
    path: /manager/
    controller: App\Controller\DefaultController::manager

# config/routes.yaml
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

# config/routes.yaml
app_logout:
    path: /logout

# config API endpoint
login:
    path: /api/login
    controller: App\Controller\Api\AuthController::login
occurrences:
    path: /api/occurrences
    controller: App\Controller\Api\OccurrenceController::index
    methods: GET
create_occurrence:
    path: /api/occurrences
    controller: App\Controller\Api\OccurrenceController::create
    methods: POST

# Occurrences Management
occurrences_management:
    path: /manager/occurrences/management
    controller: App\Controller\OccurrencesManagementController::index

occurrences_closed:
    path: /manager/occurrences/closed
    controller: App\Controller\OccurrencesClosedController::index

# register
occurrence_register:
    path: /manager/occurrence/register
    controller: App\Controller\OccurrenceRegisterController::index

# employee
employee_register:
    path: /manager/employee/register
    controller: App\Controller\EmployeeController::index



